version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 CuteCats.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
