# Generated by Django 5.1.1 on 2024-10-03 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0004_catrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catrating',
            name='value',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
