# Generated by Django 5.1.1 on 2024-10-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0005_alter_catrating_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catrating',
            options={'verbose_name': 'Оценка кота', 'verbose_name_plural': 'Оценки котов'},
        ),
    ]
